### ISSUE TITLE
[Feature request] Allow disabling [INFO] prefix in impl/std

### ISSUE THREAD

**Issue by viccuad** [Masterminds/log-go#19]
Hi,
Right now we are using `impl/std` when testing `impl/cli`. This has the effect that std prefixes all output with `[INFO]`. It would be nice if there were a way to disable at least the `[INFO] `prefix, so test outputs would match cli outputs. I'm aware that the current `impl/std` implementation writes always to the same io.Writer, as it calls the standard lib logger, but I still think that we should have a nice testing fixture for `impl/cli`, and `impl/std` seems to be it.

Maybe it can be done with an additional flag for the standard lib log package?

Cheers.

**Comment by mattfarina** [comment]
If someone is using the CLI logger and wanting to test... would it be better for them to have a test setup of the CLI logger? Consider that there is a difference between the std logger prefixes and the CLI prefixes in the text they have. If there were a way to test the CLI logger... what would you want it to do?

**Comment by viccuad** [comment]
Indeed. I just needed to be able to write to a buffer, to check the output on tests. For that, one can just create a `Logger` that satisfies `impl/cli.Logger`, but with a custom buffer instead of `os.StdX`.

Closing this.
